name: deep-learning-biology
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # General Python data science
  - python==3.9
  - matplotlib==3.3.3
  - numpy==1.19.4
  - pandas==1.1.5
  - pillow==8.0.1
  # Jupyter lab
  - jupyterlab==3.2.4
  - ipykernel==6.6.0
  - ipywidgets==7.6.5
  - progressbar==2.5
  - gdown==3.12.2
  # Machine learning and AI
  - scikit-learn==0.24.0
  - pytorch==1.7.1
  - torchvision==0.8.2
  - tensorboard==2.7.0
  - tensorboard-plugin-wit==1.8.0
  - pip
  - pip:
    - neuralnets==1.1.6.3
